### ISSUE TITLE
单生产者单消费者send方法崩溃

### ISSUE THREAD

**Issue by lrh450330** [mutouyun/cpp-ipc#17]
多进程通信，崩溃点发生在ipc.cpp line:417 code:std::memcpy(buf, data, size)，看起来像是越界了

**Comment by mutouyun** [comment]
1、一段时间后必现么？
2、不使用超出64 bytes的数据是否不会重现问题？
3、数据发送的频率有多高？

**Comment by lrh450330** [comment]
比较高的频率，千兆网卡打满800Mbps压测抓包，平均每秒90000个数据包，出现比较多次，条件是这样：没开始压测前，数据频率比较低，开启一个进程写，一个进程读(singl，single，unicast)，开启压测一段时间后关掉sender，recver工作正常，再开启sender马上挂掉，切换channel和route也是一样的过程，没来得及调试具体代码，推测是共享内存读方式占用的问题

**Comment by mutouyun** [comment]
嗯，看来是一个bug。

在大数据频繁发送的时候，会通过一个“共享内存池”加速大块数据的收发。
[find_storage] cc test failed
代表 recv 尝试获取这个池的时候出问题了。
我估计是关掉 sender 的时候，对这个池的清理出现了问题，导致 receiver 访问了错误的数据。

force_push 表示 receiver 数据接收不够及时，队列满了不得不丢弃一部分数据。
如果你的数据包都很大，并且内存充足的话，可以考虑调整下 large_msg_cache，可能会有一定改善，但要注意 cache 最多只支持 255。
另外 receiver 在接到大数据包以后，返回的 buff_t 可能是无拷贝的共享内存指针，receiver 需要尽快将数据处理完，让 buff_t 析构掉，以将共享内存指针归还到池里，否则池里的空间不够，sender 不得不拆包发送，会导致性能下降或丢包。

根据你的情况，可以尝试彻底关掉 large_msg_cache（比如把 large_msg_limit 调整得很大，这样就不会使用 cache 了）来观察下同样操作是否还有崩溃。
但这样做，大包的性能会很慢。

我明天有时间看一下 receiver 崩溃的 bug，可能需要改善下目前的 cache 实现。
如果方便的话，麻烦贴一下崩溃时的堆栈信息，谢谢。

**Comment by HelongJoy** [comment]
send大数据重启receiver后sender调用recv_cout() = 0, receiver收不到数据
rev_count : 1       // receiver 重启后
force_push: msg_id = 17, remain = 5600, size = 64
force_push: k = 0, cc = 1, rem_cc = 1
rev_count : 0     // sender 再次发送一条新数据时
rev_count : 0
large_msg_limit  已经调到8192，单个数据包4k

**Comment by mutouyun** [comment]
这周末，我会抽时间看下大数据的问题

**Comment by mutouyun** [comment]
我写了一个单对单的ut，数据大小随机 1-65536 bytes，见：[cpp-ipc/test/test_ipc.cpp](https://github.com/mutouyun/cpp-ipc/blob/master/test/test_ipc.cpp)

正常的使用没有出现问题。
我现在怀疑下面几个点：

1. 数据接收不够及时，导致消息堆积，这会让来不及收到的消息被覆盖
2. sender 本身是不需要专门 connect 的，那会导致自己重复听到自己的消息（之后会自动抛弃），对性能有一定影响
3. sender 或 receiver 的频繁重启

我下面测一下重启的问题。
@HelongJoy @lrh450330 两位如果有空，麻烦调整下我写的 ut，看看使用上是否有什么不同？

**Comment by lrh450330** [comment]
好的，这周我再测试一下，之前项目忙着上生产，现在有时间做这个事情了

**Comment by lrh450330** [comment]
另外探讨一下，IPC使用共享内存有个问题避免不了，就是上下文状态，如果其中一个进程在操作内存时未完成意外退出或者挂掉了，那这块内存就变成脏数据了。有一个解决方案是：每次内存操作增加上下文参数，进程重新起来时根据上下文参数做相关修正。当然这只是一个方案，但不是一个通用解决方案，写起来很难过。

**Comment by mutouyun** [comment]
large_msg_cache 的 255 限制是我一开始设计的时候没太多考虑频繁大块内存传输 =.=
目前这个库如果用来传视频流之类的，估计会出一些问题，我考虑做一次重构，把这个需求加上重新设计一下。

确实可以增加一些标记，但仅通过共享内存，我们很难确定对方是真的死了，还是仅仅在等待。
可以通过 socket 确认进程的死活，后面我也考虑引入类似的机制。
纯粹的共享内存还是有不少限制。

之前之所以没考虑上面这两点，是因为当时项目的应用场景：

1. 嵌入式环境，短消息（控制、状态）频繁，偶尔存在大块消息（不存在类似长时间频繁推流的情况）
2. 要求通讯建立足够早，足够轻量级，握手足够快

**Comment by mutouyun** [comment]
@lrh450330 "下午放着跑了一下午，数据大小随机[128-1024*16]，**sender重启过两次**"
请问这里的重启，是sender崩溃，还是 ctrl+c 的手动关闭重启？

**Comment by lrh450330** [comment]
@mutouyun 直接手动关闭按钮关闭，目的是测试崩溃重启仍然能正常工作

**Comment by mutouyun** [comment]
我修正了一些问题，调整了接口，添加了一个新demo：[msg_que](https://github.com/mutouyun/cpp-ipc/tree/master/demo/msg_que)
可以用它测试下单对单的收发，默认数据大小随机[128 - 1024*16]。
现在正常 ctrl-c，sender和receiver都不会出错了。

在我的机器上（i7-5500U @ 2.4 GHz，8 GB 内存，Windows 10 1909 64 位）
收发速度 2.5 GB/s 左右。

不过在我尝试调大数据大小时（改成 1024-1024*1024）出现了问题，
MapViewOfFile 等 API 会报错（估计内存不够了），从而导致了一系列奇怪的问题，并且无法自动恢复。

后面有时间我再确认下 shm 创建出问题时的 fallback。

**Comment by pabloko** [comment]
Hello, testing msg-que ive came across a possible issue where memory maps are not released (__CLS_MEM_BLOCK__ / __CLS_INFO__) the cache seems to not reuse mem blocks and they constantly grow.

https://user-images.githubusercontent.com/1850716/116994309-d5835700-acd8-11eb-81f6-1642c2c883d0.mp4

**Comment by mutouyun** [comment]
> Hello, testing msg-que ive came across a possible issue where memory maps are not released (**CLS_MEM_BLOCK** / **CLS_INFO**) the cache seems to not reuse mem blocks and they constantly grow.
> 
>  2021-05-04_13-00-32.mp4

I will check it this week.

**Comment by mutouyun** [comment]
> Hello, testing msg-que ive came across a possible issue where memory maps are not released (**CLS_MEM_BLOCK** / **CLS_INFO**) the cache seems to not reuse mem blocks and they constantly grow.
> 
>  2021-05-04_13-00-32.mp4

I tested msg-que on Windows, and watched the handles bloat through Process Hacker. I found that current large message processing algorithms create a large number of handles when the message size is uncertain. This doesn't actually cause the handle to leak, it just creates too many handles.  

This is not a very good approach, and leads to a lot of fragmented shared memory. I tweaked the algorithm so that the number of handles is now controlled by default within a reasonable range.  

See: 9aab0d4f2107058e87d120c38e8cbe03f966602c, [issue-17](https://github.com/mutouyun/cpp-ipc/tree/issue-17)

**Comment by pabloko** [comment]
testing the commit, many thanks @mutouyun for the quick answer and fix, my intention is to send PCM audio across processes (1-N), so even not being that large in size, at some point would be considerable amount of unnecessary handles retained.

So now, i still watch some grow, but I guess its normal each time buffer has to accomodate bigger buffer, at some point the grow is minimum... I think i will stick to fixed lenght to avoid issues.

**Comment by mutouyun** [comment]
You can try modifying the configuration in def.h to get better results.
- `data_length` means the default data size does not exceed this size, otherwise the single data will be split
- `large_msg_limit` means the message size larger than this size is considered large, and it will be sent all at once through the cache instead of being split
- `large_msg_align` means the size alignment of large messages (rounded up)
- `large_msg_cache` means the maximum number of large messages to cache at one time (can't be greater than 255)
